[versions]
org-mockito = "5.0.0"
org-slf4j = "2.0.6"
org-log4j = "2.20.0"
org-junit-jupiter = "5.9.2"
com-h2database = "2.2.222"
org-yaml = "2.2"

[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "org.junit.jupiter" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "org.slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "org.slf4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "org.log4j" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "org.mockito" }
h2database-h2 = { group = "com.h2database", name = "h2", version.ref = "com.h2database" }
yaml-snakeyaml  = { group = "org.yaml", name = "snakeyaml", version.ref = "org.yaml" }
